- type: entity
  id: FormPrinterMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: uniform printer machine board
  components:
  - type: MachineBoard
    prototype: PrinterDoc
    requirements:
      MatterBin: 1
      Manipulator: 2
