using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Content.Client.Message;

namespace Content.Client.FlavorText
{
    [GenerateTypedNameReferences]
    public sealed partial class FlavorText : Control
    {
        public Action<string>? OnFlavorTextChanged;

        private RichTextLabel _erpInfoLabel => CERPLabelInfo;
        private RichTextLabel _flavorTextRulesLabel => CFlavorTextRulesLabel;

        public FlavorText()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            var loc = IoCManager.Resolve<ILocalizationManager>();
            //TODO: FlavorText to TextArea
            //CFlavorTextInput.Placeholder = new Rope.Leaf(loc.GetString("flavor-text-placeholder"));
            //CFlavorTextInput.OnKeyBindDown  += _ => FlavorTextChanged();
            CFlavorTextInput.OnTextChanged += _ => FlavorTextChanged();

            _flavorTextRulesLabel.SetMarkup($"[color=yellow]{Loc.GetString(
                "Описание вашего персонажа имеет некоторые правила, созданные для того, чтобы наладить в них описание:\r\n1. Никакой биографии. \"Жил на севере\", и всё подобное, что задевает историю самого персонажа - не должно присутствовать в описании.\r\n2. Ничего из желаний, мотиваций персонажа.\r\n3. Само описание должно нести внешний вид персонажа, с учётом того, что может быть скрыто одеждой в каких-то случаях.\r\n4. Описание должно говорить о росте персонажа и его внешнем телосложении."
                )}[/color]");
            _erpInfoLabel.SetMarkup($"[color=yellow]{Loc.GetString(
                "— Уровень вашего погружения ERP на сервере, прежде всего, зависит от вашего статуса: Полное ERP, Неполное ERP, Отказ от ERP.\r\n— Полное ERP — этот статус вы ставите на свой страх и риск. Это значит, что ваш персонаж может быть подвержен любому ERP-вмешательству, даже к такому, как изнасилование, хочет ли он того, или нет. Для того, чтобы отыгрывать ERP с другим игроком, с таким же статусом, предварительного согласования в ООС-чатах вам не требуется.\r\n— Неполное ERP — возможно, самый оптимальный вариант для многих людей, которые хотят получить забавный опыт на нашем сервере, но и при этом, застраховать себя от нежелательных последствий. Другие игроки могут проявлять к вам знаки внимания, а сам ERP-отыгрыш может иметь исключительно добровольный характер. Исходя из ситуации, рекомендуется согласовать с игроком дальнейший ERP-отыгрыш.\r\n— Отказ от ERP — тут всё просто. Никто на сервере не имеет права склонять вас к какому-либо ERP-отыгрышу, а любые попытки его проявления в вашу сторону повлекут за собой дальнейшее разбирательство с администрацией.\r\n— Также, может быть такое, что статус не будет указан и вовсе. В таком случае, перед началом какого-либо ERP-отыгрыша, обязательно согласовать все дальнейшие действия с игроком в LOOC."
                )}[/color]");
        }

        public void FlavorTextChanged()
        {
            OnFlavorTextChanged?.Invoke(CFlavorTextInput.Text);
        }
        public void NoERPLabelInfo()
        {
            CERPLabelInfo.Visible = false;
        }
    }
}
