- type: job
  id: Magistrat
  name: job-name-magistrat
  description: job-description-magistrat
  playTimeTracker: JobMagistrat
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 600000
    # - !type:DepartmentTimeRequirement
    #   department: Sponsor
    #   time: 10
  startingGear: MagistratGear
  icon: "JobIconMagistrat"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
    - Command
    - Brig
    - Maintenance
    - Service
    - Security
    - Magistrate
    - Lawyer
    - IAA 
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: MagistratGear
  equipment:
    jumpsuit: ADTClothingUniformsJumpsuitWhiteDiplomatSuitL
    back: ClothingBackpackIAAFilled
    shoes: ClothingShoesBootsLaceup
    #mask: Ну что за косипор оставляет пустуе значения?
    #outerClothing: ClothingOuterRobesJudge
    eyes: ClothingEyesGlassesSunglasses
    #head: ClothingHeadHatPwig
    id: MagistratPDA
    #gloves:
    ears: ClothingHeadsetMagistrat
    #belt:
    neck: ClothingNeckLawyerbadge
    pocket1: RubberStampMagistrat
    pocket2: ADTtelescopicBaton
    underwearb: ClothingUnderwearBottomBoxersWhite # Sirena-Underwear
    socks: ClothingUnderwearSocksNormal
  underweart: ClothingUnderwearTopBraWhite # Sirena-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # Sirena-Underwear
  innerClothingSkirt: ADTClothingUniformsJumpsuitWhiteDiplomatSuitL
  satchel: ClothingBackpackSatchelIAAFilled
  duffelbag: ClothingBackpackDuffelIAAFilled
  #inhand:
  #  - BriefcaseIAAFilled






