- type: gameMap
  id: ADTTrain
  mapName: 'Train'
  mapPath: /Maps/ADTMaps/adt_train.yml
  minPlayers: 10
  maxPlayers: 70
  stations:
    ADTTrain:
      stationProto: StandardNanotrasenStation
      components:
        - type: StationNameSetup
          mapNameTemplate: 'Train "Sentipode" {0}-{1}'
          nameGenerator:
            !type:NanotrasenNameGenerator
            prefixCreator: 'ED'
        - type: StationEmergencyShuttle
          emergencyShuttlePath: /Maps/Shuttles/emergency_omega.yml # To do - add railway station
        - type: StationJobs
          overflowJobs:
            - Passenger
          availableJobs:
            #service
            Captain: [ 1, 1 ]
            HeadOfPersonnel: [ 1, 1 ]
            Bartender: [ 2, 2 ]
            Botanist: [ 3, 3 ]
            Chef: [ 2, 2 ]
            Janitor: [ 3, 3 ]
            Chaplain: [ 1, 1 ]
            Librarian: [ 1, 1 ]
            ServiceWorker: [ 2, 2 ]
            #engineering
            ChiefEngineer: [ 1, 1 ]
            AtmosphericTechnician: [ 3, 3 ]
            StationEngineer: [ 4, 4 ]
            TechnicalAssistant: [ 4, 4 ]
            #medical
            ChiefMedicalOfficer: [ 1, 1 ]
            Chemist: [ 2, 2 ]
            MedicalDoctor: [ 3, 3 ]
            Paramedic: [ 1, 1 ]
            MedicalIntern: [ 4, 4 ]
            #science
            ResearchDirector: [ 1, 1 ]
            Scientist: [ 5, 5 ]
            ResearchAssistant: [ 4, 4 ]
            Borg: [ 2, 2 ]
            #security
            HeadOfSecurity: [ 1, 1 ]
            Warden: [ 1, 1 ]
            SecurityOfficer: [ 4, 4 ]
            Detective: [ 1, 1 ]
            SecurityCadet: [ 4, 4 ]
            Lawyer: [ 2, 2 ]
            #supply
            Quartermaster: [ 1, 1 ]
            SalvageSpecialist: [ 3, 3 ]
            CargoTechnician: [ 3, 3 ]
            #civilian
            Passenger: [ -1, -1 ]
            Clown: [ 1, 1 ]
            Mime: [ 1, 1 ]
            Musician: [ 1, 1 ]
            Reporter: [ 2, 2 ]
            #ADT
            Brigmedic: [ 1, 1 ]
            ADTBlueShieldOfficer: [ 1, 1 ]
            Magistrat: [ 1, 1 ]
            ADTInvestigator: [ 1, 1 ] #ADT
            ADTSecurityCyborg: [ 1, 1 ] #ADT
            ADTEngiBorg: [ 1, 1 ] #ADT
            ADTJanitorBorg: [ 1, 1 ] #ADT
            ADTMedicalBorg: [ 1, 1 ] #ADT
            ADTServiseBorg: [ 1, 1 ] #ADT
            ADTSupplyBorg: [ 1, 1 ] #ADT
            IAA: [ 1, 1 ] # Corvax-IAA
            SeniorEngineer: [ 1, 1 ]
            SeniorPhysician: [ 1, 1 ]
            SeniorResearcher: [ 1, 1 ]
            SeniorOfficer: [ 1, 1 ]
            ADTRoboticist: [ 2, 2 ] #ADT
            ADTPathologist: [ 1 , 1 ] #ADT
