using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Tabs.PlayerTab;

[GenerateTypedNameReferences]
public sealed partial class PlayerTabEntry : PanelContainer
{
    public NetEntity? PlayerEntity;

<<<<<<< HEAD
    public PlayerTabEntry(string username, string character, string identity, string job, string antagonist, string sponsor, StyleBox styleBox, bool connected, string overallPlaytime)
=======
    public PlayerTabEntry(PlayerInfo player, StyleBoxFlat styleBoxFlat)
>>>>>>> 24e7653c984da133283457da2089e629161a7ff2
    {
        RobustXamlLoader.Load(this);

        UsernameLabel.Text = player.Username;
        if (!player.Connected)
            UsernameLabel.StyleClasses.Add("Disabled");
<<<<<<< HEAD
        JobLabel.Text = job;
        CharacterLabel.Text = character;
        if (identity != character)
            CharacterLabel.Text += $" [{identity}]";
        AntagonistLabel.Text = antagonist;
        SponsorLabel.Text = sponsor;
        BackgroundColorPanel.PanelOverride = styleBox;
        OverallPlaytimeLabel.Text = overallPlaytime;
=======
        JobLabel.Text = player.StartingJob;
        CharacterLabel.Text = player.CharacterName;
        if (player.IdentityName != player.CharacterName)
            CharacterLabel.Text += $" [{player.IdentityName}]";
        AntagonistLabel.Text = Loc.GetString(player.Antag ? "player-tab-is-antag-yes" : "player-tab-is-antag-no");
        BackgroundColorPanel.PanelOverride = styleBoxFlat;
        OverallPlaytimeLabel.Text = player.PlaytimeString;
        PlayerEntity = player.NetEntity;
>>>>>>> 24e7653c984da133283457da2089e629161a7ff2
    }
}
