- type: gameMapPool
  id: DefaultMapPool
  maps:
  - CorvaxDelta
  - Aspid
  - Atlas
  - Bagel
  - Barratry
  - Box
  - Cluster
  - Core
  - Fland
  #- Kettle
  #- Marathon
  #- Meta
  - Gemini
  - Omega
  #- Origin
  - Saltern
  #- Packed
  - ADTPacked
  - Bagel
  - Box
  #- HalloweenKettle
  #- HalloweenBoxstation
  #- HalloweenBagel
  #- HalloweenAspid
