- type: gameMapPool
  id: DefaultMapPool
  maps:
  # - Atlas
  # - Bagel
  # - Box
  # - Cluster
  # - Core
  # - Fland
  # - Marathon
  # - Meta
  # - Gemini
  # - Omega
  # - Origin
  # - Saltern
  # - Packed
  #- Reach
  - CorvaxDelta
  - CorvaxAvrite
  #- CorvaxGate
  - CorvaxSilly
  - CorvaxOutpost
  - CorvaxAstra
  - CorvaxGelta
  - ADTAtlas
  - ADTBagel
  - ADTBox
  - ADTCluster
  - ADTCore
  - ADTFland
  - ADTMarathon
  - ADTMeta
  - ADTOmega
  - ADTOrigin
  - ADTSaltern
  - ADTPacked
