- type: gameMapPool
  id: DefaultMapPool
  maps:
<<<<<<< HEAD
  # - Atlas
  # - Bagel
  # - Box
  # - Cluster
  # - Core
  # - Fland
  # - Marathon
  # - Meta
  # - Gemini
  # - Omega
  # - Origin
  # - Saltern
  # - Packed
  #- Reach
  # - CorvaxAvrite
  - ADTDelta
  - ADTAtlas
  - ADTBagel
  - ADTBox
  - ADTCluster
  - ADTCore
  - ADTFland
  - ADTMarathon
  - ADTMeta
  - ADTOmega
  - ADTOrigin
  - ADTSaltern
  - ADTPacked
  - Kilo
  - ADTTrain
  - ADTAvrite
=======
  - Atlas
  - Bagel
  - Box
  - Cluster
  - Core
  - Fland
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Origin
  - Saltern
  - Packed
  - Reach
  #- Train
>>>>>>> 24e7653c984da133283457da2089e629161a7ff2
