- type: gameMapPool
  id: DefaultMapPool
  maps:
  - CorvaxDelta
  - CorvaxAvrite
  - Aspid
  - Barratry
  #- Cluster
  - HalloweenCluster
  #- Core
  - Fland
  - Kettle
  - Marathon
  - Meta
  - Omega
  - Origin
  - Saltern
  #- Packed
  - ADTPacked
  - Bagel
  - Box
