#Misc outfit startingGear definitions.

#Skeleton Biker - Just a skeleton now
- type: startingGear
  id: SkeletonBiker
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
    back: ClothingBackpack
    head: ClothingHeadBandSkull
    eyes: ClothingEyesGlassesSunglasses
    outerClothing: ClothingOuterCoatGentle
    gloves: ClothingHandsGlovesFingerless
    shoes: ClothingShoesBootsJack
    id: PassengerPDA
    ears: ClothingHeadsetGrey
<<<<<<< HEAD
  innerClothingSkirt: ClothingUniformJumpskirtColorBlack
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

#Space Ninja Outfit
- type: startingGear
  id: SpaceNinjaGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNinja
    # belt holds katana so satchel has the tools for sabotaging things
    back: ADTClothingBackpackSatchelninjaTools
    mask: ClothingMaskNinja
    head: ClothingHeadHelmetSpaceNinja
    eyes: ClothingEyesVisorNinja
    gloves: ClothingHandsGlovesSpaceNinja
    outerClothing: ClothingOuterSuitSpaceNinja
    shoes: ClothingShoesSpaceNinja
    id: AgentIDCard
    ears: ClothingHeadsetGrey
    pocket1: SpiderCharge
    pocket2: PinpointerStation
    belt: EnergyKatana
    suitstorage: OxygenTankFilled
  inhand:
    - JetpackBlackFilled
=======
  storage:
    back:
    - BoxSurvival
>>>>>>> 24e7653c984da133283457da2089e629161a7ff2

#Deathsquad Outfit
- type: startingGear
  id: DeathSquadGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDeathSquad
    back: ClothingBackpackDeathSquad
    mask: ClothingMaskGasDeathSquad
    eyes: ClothingEyesHudSecurity
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitDeathsquad
    suitstorage: AirTankFilled
    shoes: ClothingShoesBootsMagAdv
    id: DeathsquadPDA
    pocket1: EnergySword
    pocket2: EnergyShield
    belt: ClothingBeltMilitaryWebbingMedFilled
  storage:
    back:
    - BoxSurvivalEngineering
    - WeaponPulseRifle
    - WeaponPulsePistol
    - WeaponRevolverMateba
    - SpeedLoaderMagnumAP
    - SpeedLoaderMagnumAP
    - BoxFlashbang
    - ToolDebug # spanish army knife
    - WelderExperimental
    - Hypospray
    - DeathAcidifierImplanter # crew will try to steal their amazing hardsuits
    - FreedomImplanter

# Syndicate Operative Outfit - Civilian
- type: startingGear
  id: SyndicateOperativeGearCivilian
  equipment:
<<<<<<< HEAD
    head: ClothingHeadHatOutlawHat
    jumpsuit: ClothingUniformJumpsuitOperative
    mask: CigaretteSyndicate
  innerClothingSkirt: ClothingUniformJumpsuitOperative

# Syndicate Operative Outfit - Barratry
- type: startingGear
  id: SyndicateOperativeGearExtremelyBasic
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicateOperative
    shoes: ClothingShoesBootsCombatFilled
    gloves: ClothingHandsGlovesColorBlack
  innerClothingSkirt: ClothingUniformJumpsuitOperative
  satchel: ClothingBackpackDuffelSyndicateOperative
  duffelbag: ClothingBackpackDuffelSyndicateOperative

#Syndicate Operative Outfit - Basic
- type: startingGear
  id: SyndicateOperativeGearBasic
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicateOperative
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsCombatFilled
    pocket1: BaseUplinkRadio40TC
    id: SyndiPDA
  innerClothingSkirt: ClothingUniformJumpsuitOperative
  satchel: ClothingBackpackDuffelSyndicateOperative
  duffelbag: ClothingBackpackDuffelSyndicateOperative

#Syndicate Operative Outfit - Full Kit
- type: startingGear
  id: SyndicateOperativeGearFull
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicateOperative
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudSyndicate
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitSyndie
    shoes: ClothingShoesBootsCombatFilled
    id: SyndiPDA
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: BaseUplinkRadio40TC
    belt: ClothingBeltMilitaryWebbing
  innerClothingSkirt: ClothingUniformJumpskirtOperative
  satchel: ClothingBackpackDuffelSyndicateOperative
  duffelbag: ClothingBackpackDuffelSyndicateOperative

#Nuclear Operative Commander Gear
- type: startingGear
  id: SyndicateCommanderGearFull
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicateOperative
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudSyndicate
    ears: ClothingHeadsetAltSyndicate
    neck: SyndicateWhistle
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitSyndieCommander
    shoes: ClothingShoesBootsCombatFilled
    id: SyndiPDA
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: BaseUplinkRadio40TC
    belt: ClothingBeltMilitaryWebbing
  inhand:
    - NukeOpsDeclarationOfWar
  innerClothingSkirt: ClothingUniformJumpskirtOperative
  satchel: ClothingBackpackDuffelSyndicateOperative
  duffelbag: ClothingBackpackDuffelSyndicateOperative

#Nuclear Operative Medic Gear
- type: startingGear
  id: SyndicateOperativeMedicFull
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicateOperativeMedic
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudSyndicate
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitSyndieMedic
    shoes: ClothingShoesBootsMagSyndie
    id: SyndiAgentPDA
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: BaseUplinkRadio40TC
    suitstorage: SyringeGun
    belt: ClothingBeltMilitaryWebbingMedFilled
  innerClothingSkirt: ClothingUniformJumpskirtOperative
  satchel: ClothingBackpackDuffelSyndicateOperativeMedic
  duffelbag: ClothingBackpackDuffelSyndicateOperativeMedic

# Syndicate Footsoldier Gear
- type: startingGear
  id: SyndicateFootsoldierGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    head: ClothingHeadHelmetSwatSyndicate
    mask: ClothingMaskGas
    outerClothing: ClothingOuterArmorBasic
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpackFilled
=======
    jumpsuit: ClothingUniformJumpsuitSyndieFormal
    back: ClothingBackpackDuffelSyndicate
>>>>>>> 24e7653c984da133283457da2089e629161a7ff2
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesColorBlack
    id: SyndiPDA
    ears: ClothingHeadsetAltSyndicate

# Syndicate Footsoldier Gear - No Headset
- type: startingGear
  id: SyndicateFootsoldierGearRuin
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    head: ClothingHeadHelmetSwatSyndicate
    mask: ClothingMaskGas
    outerClothing: ClothingOuterArmorBasic
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpack
    shoes: ClothingShoesBootsCombat
    id: SyndiPDA
  storage:
    back:
    - BoxSurvival

# Syndicate Footsoldier Gear
- type: startingGear
  id: SyndicateFootsoldierGear
  parent: SyndicateFootsoldierGearRuin
  equipment:
    ears: ClothingHeadsetAltSyndicate

# Nanotrasen Paramilitary Unit Gear
- type: startingGear
  id: NanotrasenParamilitaryGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHelmetSwat
    mask: ClothingMaskGasSwat
    outerClothing: ClothingOuterArmorBasicSlim
    ears: ClothingHeadsetSecurity
    gloves: ClothingHandsGlovesCombat
  storage:
    back:
    - BoxSurvivalSecurity
    - Flash
    - MagazinePistol

#CBURN Unit Gear - Full Kit
- type: startingGear
  id: CBURNGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    back: ClothingBackpackDuffelCBURN
<<<<<<< HEAD
    mask: ClothingMaskGasExplorer
    eyes: ClothingEyesHudSecurity
=======
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
>>>>>>> 24e7653c984da133283457da2089e629161a7ff2
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitCBURN
    shoes: ADTClothingShoesBootsMagERT
    id: CBURNPDA
    pocket1: RadioHandheld
    pocket2: WeaponPulsePistol
    suitstorage: OxygenTankFilled
    belt: ClothingBeltBandolier
<<<<<<< HEAD
    underwearb: ClothingUnderwearBottomBoxersWhite # Sirena-Underwear
  underweart: ClothingUnderwearTopBraWhite # Sirena-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # Sirena-Underwear
  innerClothingSkirt: ClothingUniformJumpsuitColorBrown
  satchel: ClothingBackpackDuffelCBURN
  duffelbag: ClothingBackpackDuffelCBURN
=======
  storage:
    back:
    - BoxSurvivalEngineering
    - WeaponShotgunDoubleBarreled
    - BoxShotgunIncendiary
    - GrenadeFlashBang
    - PillAmbuzolPlus
    - PillAmbuzol
>>>>>>> 24e7653c984da133283457da2089e629161a7ff2

- type: startingGear
  id: BoxingKangarooGear
  equipment:
    gloves: ClothingHandsGlovesBoxingBlue

- type: startingGear
  id: MobMonkeyGear
  equipment:
    head: ClothingHeadHatTophat
    ears: ClothingHeadsetService
    jumpsuit: ClothingUniformJumpsuitJacketMonkey
    id: PunPunIDCard

# DeathMatch Gear

- type: startingGear
  id: DeathMatchGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorWhite
    shoes: ClothingShoesBootsJack
    ears: ClothingHeadsetGrey
    gloves: ClothingHandsGlovesFingerless
  inhand:
    - WeaponMeleeToolboxRobust

#Brigmedic

<<<<<<< HEAD
#- type: startingGear
#  id: BrigmedicGear
#  equipment:
#    jumpsuit: ClothingUniformJumpsuitBrigmedic
#    outerClothing: ClothingOuterCoatAMG
#    back: ClothingBackpackBrigmedicFilled
#    shoes: ClothingShoesColorRed
#    gloves: ClothingHandsGlovesNitrile
#    eyes: ClothingEyesHudMedical
#    head: ClothingHeadHatBeretBrigmedic
#    id: BrigmedicPDA
#    ears: ClothingHeadsetBrigmedic
#    mask: ClothingMaskBreathMedicalSecurity
#    belt: ClothingBeltMedicalFilled
#  innerclothingskirt: ClothingUniformJumpskirtBrigmedic
#  satchel: ClothingBackpackSatchelBrigmedicFilled
#  duffelbag: ClothingBackpackDuffelBrigmedicFilled
=======
- type: startingGear
  id: BrigmedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBrigmedic
    outerClothing: ClothingOuterCoatAMG
    back: ClothingBackpackBrigmedic
    shoes: ClothingShoesColorRed
    gloves: ClothingHandsGlovesNitrile
    eyes: ClothingEyesHudMedical
    head: ClothingHeadHatBeretBrigmedic
    id: BrigmedicPDA
    ears: ClothingHeadsetBrigmedic
    mask: ClothingMaskBreathMedicalSecurity
    belt: ClothingBeltMedicalFilled
>>>>>>> 24e7653c984da133283457da2089e629161a7ff2

# Aghost
- type: startingGear
  id: MobAghostGear
  equipment:
    back: ClothingBackpackSatchelHolding
    id: AdminPDA
  storage:
    back:
    - GasAnalyzer
    - trayScanner
    - AccessConfiguratorUniversal

#Gladiator with spear
- type: startingGear
  id: GladiatorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitGladiator
    back: SpearBone
    head: ClothingHeadHatGladiator
    shoes: ClothingShoesCult

#Ash Walker
- type: startingGear
  id: AshWalker
  equipment:
    jumpsuit: ClothingUniformJumpsuitGladiator
    outerClothing: ClothingOuterArmorBone
    back: SpearBone
    head: ClothingHeadHelmetBone
    shoes: ClothingShoesCult

#Banana Clown
- type: startingGear
  id: BananaClown
  equipment:
    id: ClownPDA
    back: ClothingBackpackClown
    shoes: ClothingShoesClownBanana
    jumpsuit: ClothingUniformJumpsuitClownBanana
    mask: ClothingMaskClownBanana
    pocket1: BikeHorn
    pocket2: ClownRecorder

# Passenger but without the ID, bag, or headset
- type: startingGear
  id: LimitedPassengerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorGrey
    shoes: ClothingShoesColorBlack

#Clown Troupe
- type: startingGear
  id: ClownTroupe
  equipment:
    jumpsuit: ClothingUniformJumpsuitClown
    shoes: ClothingShoesClown
    id: ClownPDA
    back: ClothingBackpackClown
    ears: ClothingHeadsetService
    mask: ClothingMaskClown
    pocket1: BikeHorn
    pocket2: ClownRecorder

#Lost Cargo Tech
- type: startingGear
  id: LostCargoTechGearSuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitCargo
    shoes: ClothingShoesColorBlack
    head: ClothingHeadHatCargosoft
    id: CargoPDA
    back: ClothingBackpackCargo
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool

- type: startingGear
  id: LostCargoTechGearCoat
  equipment:
    jumpsuit: ClothingUniformJumpsuitCargo
    shoes: ClothingShoesBootsWinterCargo
    head: ClothingHeadHatCargosoft
    id: CargoPDA
    back: ClothingBackpackDuffelCargo
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool
    outerClothing: ClothingOuterWinterCargo

#Traveling Chef
- type: startingGear
  id: TravelingChef
  equipment:
    jumpsuit: ClothingUniformJumpsuitChef
    shoes: ClothingShoesColorWhite
    id: ChefPDA
    back: ClothingBackpackSatchel
    ears: ClothingHeadsetService
    belt: ClothingBeltChef

#CMO Disaster Victim
- type: startingGear
  id: DisasterVictimCMO
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMO
    shoes: ClothingShoesColorBrown
    head: ClothingHeadMirror
    neck: ClothingCloakCmo
    id: CMOPDA
    back: ClothingBackpackMedical
    ears: ClothingHeadsetCMO
    belt: ClothingBeltMedical
    outerClothing: ClothingOuterCoatLabCmo

- type: startingGear
  id: DisasterVictimCMOAlt
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMOTurtle
    shoes: ClothingShoesColorBrown
    head: ClothingHeadHatBeretCmo
    neck: ClothingNeckMantleCMO
    id: CMOPDA
    back: ClothingBackpackSatchelMedical
    ears: ClothingHeadsetCMO
    belt: ClothingBeltMedical
    outerClothing: ClothingOuterCoatLabCmo

#Captain Disaster Victim
- type: startingGear
  id: DisasterVictimCaptain
  equipment:
    jumpsuit: ClothingUniformJumpsuitCaptain
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    head: ClothingHeadHatCaptain
    neck: ClothingNeckCloakCap
    id: CaptainPDA
    back: ClothingBackpackCaptain
    ears: ClothingHeadsetAltCommand
    outerClothing: ClothingOuterArmorCaptainCarapace

- type: startingGear
  id: DisasterVictimCaptainAlt
  equipment:
    jumpsuit: ClothingUniformJumpsuitCapFormal
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    head: ClothingHeadHatCapcap
    neck: ClothingNeckMantleCap
    id: CaptainPDA
    back: ClothingBackpackSatchelCaptain
    ears: ClothingHeadsetAltCommand
    outerClothing: ClothingOuterArmorCaptainCarapace

#RD Disaster Victim
- type: startingGear
  id: DisasterVictimRD
  equipment:
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    shoes: ClothingShoesColorBrown
    head: ClothingHeadHatBeretRND
    neck: ClothingNeckCloakRd
    id: RnDPDA
    back: ClothingBackpackScience
    ears: ClothingHeadsetRD
    outerClothing: ClothingOuterCoatRD

- type: startingGear
  id: DisasterVictimRDAlt
  equipment:
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    shoes: ClothingShoesColorBrown
    head: ClothingHeadHatBeretRND
    neck: ClothingNeckMantleRD
    id: RnDPDA
    back: ClothingBackpackSatchelScience
    ears: ClothingHeadsetRD
    outerClothing: ClothingOuterCoatRD
