- type: department
  id: Cargo
  description: department-Cargo-description
  color: "#A46106"
  roles:
  - CargoTechnician
  - Quartermaster
  - SalvageSpecialist
  - ADTSupplyBorg

- type: department
  id: Civilian
  description: department-Civilian-description
  color: "#9FED58"
  weight: -10
  roles:
  - Bartender
  - Borg
  - Botanist
  - Boxer
  - Chaplain
  - Chef
  - Clown
  - HeadOfPersonnel
  - Janitor
  - Librarian
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Visitor
  - Zookeeper
  # - Detective
  - ServiceWorker
  - ADTServiseBorg
  - ADTJanitorBorg

- type: department
  id: Command
  description: department-Command-description
  color: "#334E6D"
  roles:
  - Captain
  - CentralCommandOfficial
  - IAA
  - Magistrat
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfPersonnel
  - HeadOfSecurity
  - ResearchDirector
  - Quartermaster
  - ADTBlueShieldOfficer
  primary: false
  weight: 100

- type: department
  id: Engineering
  description: department-Engineering-description
  color: "#EFB341"
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - SeniorEngineer
  - StationEngineer
  - TechnicalAssistant
  - ADTEngiBorg

- type: department
  id: Medical
  description: department-Medical-description
  color: "#52B4E9"
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - MedicalDoctor
  - MedicalIntern
  - ADTPathologist
  - Psychologist
  - Paramedic
  - SeniorPhysician
  - ADTMedicalBorg

- type: department
  id: Security
  description: department-Security-description
  color: "#DE3A3A"
  weight: 20
  roles:
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  - SeniorOfficer
  - Detective
  - Warden
  - Brigmedic
  - ADTInvestigator
  - ADTSecurityCyborg

- type: department
  id: Science
  description: department-Science-description
  color: "#D381C9"
  roles:
  - ResearchDirector
  - SeniorResearcher
  - Scientist
  - ResearchAssistant
  - ADTRoboticist # ADT Roboticist job

- type: department
  id: Specific
  description: department-Specific-description
  color: "#9FED58"
  weight: 10
  roles:
  - Boxer
  - Reporter
  - Zookeeper
  - Psychologist
  primary: false

- type: department
  id: Law
  description: department-Command-description
  color: "#E9967A"
  roles:
  - Lawyer
  - IAA
  - Magistrat

# - type: department
#   id: Sponsor
#   description: department-Command-description
#   color: "#E9967A"
#   roles:
#   - Sponsor
