- type: antag
  id: Changeling
  name: roles-antag-changeling-name
  antagonist: true
  setPreference: true
  objective: roles-antag-changeling-objective
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 270000 #75 hrs
