- type: entity
  parent: BaseMob
  id: ADTBaseBorgChassisSyndicate
  name: cyborg
  description: A man-machine hybrid that assists in station activity. They love being asked to state their laws over and over.
  save: false
  abstract: true
  components:
  - type: Reactive
    groups:
      Acidic: [Touch]
  - type: DamageOnHighSpeedImpact
    damage:
      types:
        Blunt: 5
    soundHit:
      path: /Audio/Effects/hit_kick.ogg
  - type: CombatMode
  - type: NoSlip
  - type: StaticPrice
    price: 12500
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeCircle
          radius: 0.35
        density: 150
        mask:
        - MobMask
        layer:
        - MobLayer
  - type: MovementSpeedModifier
    baseWalkSpeed : 2.5
    baseSprintSpeed : 4.5
  - type: Sprite
    sprite: Mobs/Silicon/chassis.rsi
  - type: RotationVisuals
    horizontalRotation: 90
  - type: MobState
    allowedStates:
    - Alive
    - Critical
    - Dead
  - type: MobThresholds
    thresholds:
      0: Alive
      200: Critical
      325: Dead
    stateAlertDict:
      Alive: BorgHealth
      Critical: BorgCrit
      Dead: BorgDead
    showOverlays: false
    allowRevives: true
  - type: HealthExaminable
    examinableTypes:
      - Blunt
      - Slash
      - Piercing
      - Heat
      - Shock
    locPrefix: silicon
  - type: UserInterface
    interfaces:
    - key: enum.SiliconLawsUiKey.Key
      type: SiliconLawBoundUserInterface
    - key: enum.BorgUiKey.Key
      type: BorgBoundUserInterface
    - key: enum.StrippingUiKey.Key
      type: StrippableBoundUserInterface
  - type: ActivatableUI
    key: enum.BorgUiKey.Key
  - type: SiliconLawBound
  - type: SiliconLawProvider
    laws: SyndicateStatic
  - type: IonStormTarget
  - type: Strippable
  - type: InventorySlots
  - type: Inventory
    templateId: borg
  - type: Hands
    showInHands: false
  - type: IntrinsicRadioReceiver
  - type: IntrinsicRadioTransmitter
    channels:
    - Binary
    - Syndicate
  - type: ActiveRadio
    channels:
    - Binary
    - Syndicate
  - type: ZombieImmune
  - type: Repairable
    doAfterDelay: 10
    allowSelfRepair: false
  - type: BorgChassis
    maxModules: 6
    moduleWhitelist:
      tags:
      - ADTBorgModuleSyndicate
      - BorgModuleGeneric
      - BorgModuleCargo
      - BorgModuleEngineering
      - BorgModuleJanitor
      - BorgModuleMedical
      - BorgModuleService
  - type: WiresPanel
  - type: ActivatableUIRequiresPanel
  - type: Wires
    layoutId: Borg
  - type: NameIdentifier
    group: Silicon
  - type: ContainerContainer
    containers:
      borg_brain: !type:ContainerSlot { }
      cell_slot: !type:ContainerSlot { }
      borg_module: !type:Container { }
      part-container: !type:Container
  - type: PowerCellSlot
    cellSlotId: cell_slot
    fitsInCharger: true
  - type: PowerCellDraw
    drawRate: 0.6
  - type: ItemSlots
    slots:
      cell_slot:
        name: power-cell-slot-component-slot-name-default
  - type: Body
  - type: StatusEffects
    allowed:
    - Stun
    - KnockedDown
    - SlowedDown
  - type: TypingIndicator
    proto: robot
  - type: Speech
    speechVerb: Robotic
    speechSounds: Pai
  - type: UnblockableSpeech
  - type: Construction
    graph: Cyborg
    containers:
    - part-container
    - cell_slot
  - type: Flashable
  - type: Damageable
    damageContainer: Silicon
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 175
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          path: /Audio/Machines/warning_buzzer.ogg
          params:
            volume: 5
    - trigger:
        !type:DamageTrigger
        damage: 425
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          path: /Audio/Effects/metalbreak.ogg
      - !type:EmptyContainersBehaviour
        containers:
        - borg_brain
        - borg_module
        - cell_slot
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: HandheldLight
    toggleOnInteract: false
    wattage: 0.2
    blinkingBehaviourId: blinking
    radiatingBehaviourId: radiating
  - type: LightBehaviour
    behaviours:
    - !type:FadeBehaviour
      id: radiating
      maxDuration: 2.0
      startValue: 3.0
      endValue: 2.0
      isLooped: true
      reverseWhenFinished: true
    - !type:PulseBehaviour
      id: blinking
      interpolate: Nearest
      maxDuration: 1.0
      minValue: 0.1
      maxValue: 2.0
      isLooped: true
  - type: ToggleableLightVisuals
  - type: PointLight
    enabled: false
    mask: /Textures/Effects/LightMasks/cone.png
    autoRot: true
    radius: 4
    netsync: false
  - type: Pullable
  - type: Puller
    needsHands: false
  - type: StandingState
  - type: Tag
    tags:
    - ShoesRequiredStepTriggerImmune
    - DoorBumpOpener
  - type: Emoting
  - type: GuideHelp
    guides:
      - Cyborgs
  - type: NpcFactionMember
    factions:
    - Syndicate
  - type: Access
    enabled: true
    tags:
    - NuclearOperative
    - SyndicateAgent
  - type: Lock
    locked: true
  - type: ActivatableUIRequiresLock
  - type: AccessReader
    access: [["NuclearOperative"], ["SyndicateAgent"]]
  - type: ShowSecurityIcons
