meta:
  format: 6
  postmapinit: false
tilemap: {}
entities:
- proto: FaxMachineBase
  entities:
  - uid: 1
    components:
    - pos: 2.5,4.5
      type: Transform
    - name: NT-SEC Орел
      type: FaxMachine
...
