- type: job
  id: Librarian
  name: job-name-librarian
  description: job-description-librarian
  playTimeTracker: JobLibrarian
  startingGear: LibrarianGear
  icon: "JobIconLibrarian"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance

- type: startingGear
  id: LibrarianGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    id: LibrarianPDA
    ears: ClothingHeadsetService
    pocket1: d10Dice
    belt: BooksBag
    pocket2: HandLabeler # for making named bestsellers
<<<<<<< HEAD
    underwearb: ClothingUnderwearBottomBoxersWhite # Sirena-Underwear
    socks: ClothingUnderwearSocksNormal
  underweart: ClothingUnderwearTopBraWhite # Sirena-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # Sirena-Underwear
  inhand:
    - BriefcaseBrownFilled
  innerClothingSkirt: ClothingUniformJumpskirtLibrarian # Corvax-Resprite
  satchel: ClothingBackpackSatchelLibrarianFilled
  duffelbag: ClothingBackpackDuffelLibrarianFilled
=======
  storage:
    back:
    - BoxSurvival
    - BookRandom
>>>>>>> a9610d4f850c7227ef298de535153c3746462b2a
