- type: antag
  id: HeadRev
  name: roles-antag-rev-head-name
  antagonist: true
  setPreference: true
  objective: roles-antag-rev-head-objective
<<<<<<< HEAD
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 72000 #20 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 #10 hrs
    - !type:DepartmentTimeRequirement
      department: Command
      time: 36000 #10 hours
=======
  guides: [ Revolutionaries ]
>>>>>>> 24e7653c984da133283457da2089e629161a7ff2

- type: antag
  id: Rev
  name: roles-antag-rev-name
  antagonist: true
  setPreference: false
  objective: roles-antag-rev-objective
  guides: [ Revolutionaries ]

- type: startingGear
  id: HeadRevGear
  storage:
    back:
    - Flash
    - ClothingEyesGlassesSunglasses
