- type: job
  id: ADTSupplyBorg
  name: JobADTSupplyBorg
  description: job-description-borg
  playTimeTracker: JobSupplyBorg
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 216000 #60 hrs
  canBeAntag: false
  icon: JobIconBorg
  supervisors: job-supervisors-rd
  jobEntity: ADTPlayerBorgMining
