name: "Labels: PR"

on:
- pull_request_target

jobs:
  labeler:
    if: github.actor != 'IanComradeBot'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"